#!/bin/sh

#
# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh does
#       not find so, but you have some other shells available, you may want to
#       execute the script with one of these shells instead.
#       See the documentation for a way to specify the shell.
#
#   (2) Busybox and similar reduced shells will NOT work, because this script
#       requires all of these POSIX shell features:
#         * functions;
#         * expansions "$var", "${var}", "${var:-default}", "${var+SET}",
#           "${var#prefix}", "${var%suffix}", and "$( cmd )";
#         * compound commands having a testable exit status, especially "case";
#         * various built-in commands including "command", "set", and "trap".
#
#   Important for patching:
#
#   (1) If you distribute this script as part of a larger package, make sure you
#       leave the above value of "APP_HOME" in this script, so the script as well
#       as all other scripts sourced by it will operate as expected.
#
#   (2) Avoid depending upon User since variations between the shells People
#       use will cause failures below (in particular, if Busybox's ash
#       tries to match an open quote by searching for the next one in the
#       entire file).
#
#   (3) Put the entire script as one "set -e" statement to make the entire
#       script fail on any error.
#

set -e

APP_HOME=$( cd "${APP_HOME:-./}" && pwd -P ) || exit

APP_NAME="Gradle"
APP_JAR="${APP_HOME}/gradle/wrapper/gradle-wrapper.jar"

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='" -Xmx64m" "-Xms64m"'

# Use the maximum available, or set MAX_FD != maximum.
MAX_FD="maximum"

warn () {
    echo "$*" >&2
}

die () {
    echo
    echo "$*"
    echo
    exit 1
}

# OS specific support (must be 'true' or 'false').
darwin=false
msys=false
cygwin=false
nongnu=false
case "$( uname )" in                #(
  Darwin* )         darwin=true  ;; #(
  MSYS* )           msys=true   ;; #(
  CYGWIN* )         cygwin=true  ;; #(
  NONSTOP* )        nongnu=true ;; #(
esac

if [ "$1" = "-noproxy" ]; then
    shift
    noproxy=true
fi

prog="$0"
while [ -h "$prog" ] ; do
    ls=$( ls -ld "$prog" )
    link=$( expr "$ls" : '.*-> \(.*\)$' )
    if expr "$link" : '/.*' > /dev/null; then
        prog="$link"
    else
        prog=$( cd "$( dirname "$prog" )" && pwd -P )/$( basename "$prog" )
    fi
done

PROG_DIR=$( cd "$( dirname "$prog" )" && pwd -P )

exec "$JAVA_HOME"/bin/java $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS \
    -classpath "$APP_JAR" \
    org.gradle.wrapper.GradleWrapperMain \
    "$@"
