-keep class com.qorithone.qorith.** { *; }
-keepclassmembers class com.qorithone.qorith.** { *; }
-keep class androidx.media3.** { *; }
-keep class androidx.compose.** { *; }
-keep class com.google.dagger.hilt.** { *; }
